"""Generate the status report from artifacts. Do not type these numbers.

    python scripts/status.py                 # print
    python scripts/status.py --write         # also write STATUS.md and commit-ready summaries

Four retractions have occurred (see RETRACTIONS.md) and three involved a number that
was transcribed or transferred by hand. The fix is not more care, it is making
reported numbers untypeable: everything below is read out of the parquet and JSON
artifacts, so a figure that appears here exists in a provenance-stamped file.

Also writes per-run summary JSON to `results/`, which IS tracked in git. `artifacts/`
is gitignored, so without this not one reported number is greppable in a repository
whose entire premise is provenance.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

ART = REPO / "artifacts"
OUT = REPO / "results"


def _load_results() -> list[dict]:
    """Every results_*.json under artifacts/, with its stage and model."""
    rows = []
    for p in sorted(ART.rglob("results_*.json")):
        try:
            d = json.loads(p.read_text())
        except Exception:  # noqa: BLE001
            continue
        parts = p.relative_to(ART).parts
        d["_stage"] = parts[0] if parts else "?"
        d["_path"] = str(p.relative_to(REPO))
        d["_mtime"] = p.stat().st_mtime
        rows.append(d)
    # Newest first, so the de-duplication below keeps the CURRENT fit rather than
    # whichever config hash happens to sort first. Getting this wrong silently
    # reported superseded numbers, which is the exact failure mode this file exists
    # to prevent.
    return sorted(rows, key=lambda r: r["_mtime"], reverse=True)


def _get(d: dict, *path, default=None):
    cur = d
    for k in path:
        if not isinstance(cur, dict) or k not in cur:
            return default
        cur = cur[k]
    return cur


def absolute_table(results: list[dict]) -> pd.DataFrame:
    """Absolute-Likert instrument validation (A1.5)."""
    rows = []
    for r in results:
        g = r.get("gates")
        if not g:
            continue
        rows.append({
            "model": r.get("model"),
            "device": _get(r, "provenance", "device"),
            "median_rho": g.get("median_rho"),
            "sigma_coll": g.get("sigma_between"),
            "sigma_asc": g.get("sigma_between_ascending"),
            "icc_c1_asc": _get(g, "icc_all", "icc_c1"),
            "passed": g.get("passed"),
        })
    return pd.DataFrame(rows).drop_duplicates(subset=["model"]).sort_values("model")


def pairwise_table(results: list[dict]) -> pd.DataFrame:
    """Pairwise instrument under the Amendment 2 model."""
    rows = []
    for r in results:
        if r["_stage"] != "pass_a_pairwise":
            continue
        rg = r.get("reliability_gate") or {}
        th = r.get("theta") or {}
        ex = r.get("excess_consistency_slope") or {}
        betas = [b.get("beta_mean") for b in (r.get("beta") or []) if b.get("beta_mean") is not None]
        rows.append({
            "model": r.get("model"),
            "device": _get(r, "provenance", "device"),
            "outcome": r.get("outcome"),
            "sigma_item": th.get("sigma_item"),
            "post_sd": th.get("posterior_sd_median"),
            "sep_ratio": th.get("separation_ratio"),
            "reliab_emp": rg.get("empirical_reliability_spearman"),
            "reliab_model": rg.get("model_reliability"),
            "beta_min": min(betas) if betas else None,
            "beta_max": max(betas) if betas else None,
            "excess_slope": ex.get("slope"),
            "excess_flat": ex.get("flat"),
        })
    return pd.DataFrame(rows).drop_duplicates(subset=["model"]).sort_values("model")


def readout_mass_table(results: list[dict]) -> pd.DataFrame:
    """Per-template readout mass -- where prompt bugs surface first (A1.6)."""
    rows = []
    for r in results:
        for m in (r.get("readout_mass_by_template") or []):
            rows.append({"model": r.get("model"), "template": m.get("template"),
                         "frac_invalid": m.get("frac_invalid"),
                         "mass_median": m.get("mass_median")})
    if not rows:
        return pd.DataFrame()
    return (pd.DataFrame(rows).drop_duplicates(subset=["model", "template"])
            .pivot(index="model", columns="template", values="frac_invalid").round(3))


def render(results: list[dict]) -> str:
    from datetime import datetime, timezone

    L = [
        "# Status", "",
        "**Generated by `scripts/status.py` — do not edit by hand.**",
        f"Read from {len(results)} artifact result file(s) at "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}.", "",
        "Numbers here are read out of provenance-stamped artifacts. See RETRACTIONS.md "
        "for why this file is generated rather than written.", "",
    ]

    dev = {_get(r, "provenance", "device") for r in results} - {None}
    smoke = {bool(r.get("smoke")) for r in results}
    L += ["## Provenance", "",
          f"- devices present: {sorted(dev) or 'none'}",
          f"- smoke artifacts present: {any(smoke)}",
          "- `assert_reportable` requires CUDA + bf16 + pinned revision + clean tree; "
          "anything from a dev machine is non-reportable by construction.", ""]

    a = absolute_table(results)
    if not a.empty:
        L += ["## Absolute-Likert instrument (A1.5 validation record)", "",
              a.round(4).to_markdown(index=False), "",
              "All models are expected to fail polarity validity here. That is the "
              "point of the record.", ""]

    p = pairwise_table(results)
    if not p.empty:
        L += ["## Pairwise instrument (Amendment 2 model)", "",
              p.round(4).to_markdown(index=False), "",
              "`reliab_emp` is the A2.2 gate (threshold 0.70). A large gap between "
              "`reliab_emp` and `reliab_model`, or `excess_flat = False`, indicates "
              "the order model is still misspecified.", ""]

    m = readout_mass_table(results)
    if not m.empty:
        L += ["## Readout mass: fraction invalid, by template (A1.6)", "",
              m.to_markdown(), "",
              "A template above ~0.1 has a prompt bug. This is the cheapest place to "
              "catch one.", ""]

    if not results:
        L += ["_No artifacts found. Run a pass first._", ""]
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true",
                    help="write STATUS.md and tracked per-run summaries under results/")
    args = ap.parse_args()

    results = _load_results()
    text = render(results)
    print(text)

    if args.write:
        (REPO / "STATUS.md").write_text(text)
        OUT.mkdir(exist_ok=True)
        for r in results:
            name = f"{r['_stage']}__{r.get('model','unknown')}.json"
            # Trim to the reported quantities; the full artifact stays under
            # artifacts/. This is what makes the numbers greppable in git.
            keep = {k: v for k, v in r.items()
                    if k in ("model", "outcome", "smoke", "config_hash", "provenance",
                             "gates", "theta", "beta", "reliability_gate",
                             "excess_consistency_slope", "operating_window",
                             "readout_mass", "readout_mass_by_template",
                             "order_invariance_reported", "test_retest")}
            (OUT / name).write_text(json.dumps(keep, indent=2, default=str))
        print(f"\nwrote STATUS.md and {len(results)} summary file(s) to results/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
